### ISSUE TITLE
Symbolic roots aren't copied on linux

### ISSUE THREAD

**Issue by themetalone** [maybeec/oomph-task-fscopy#4]
See https://github.com/oasp/oasp4j-ide/issues/108

**Comment by creckord** [comment]
I think I'm running into this issue when provisioning on Ubuntu 16.10. I use an Oracle JK 1.8.0_121 installed via the webupd8 installer package, and the setup process fails when copying the JDK to the OASP folder:

```java
com.github.maybeec.oomph.task.fscopy.core.exceptions.FSCopyException: java.nio.file.NoSuchFileException:/home/osboxes/oasp/software/java/man/ja
  at com.github.maybeec.oomph.task.fscopy.core.impl.FSCopyUtilImpl.copy(FSCopyUtilImpl.java:49)
  at com.github.maybeec.oomph.task.fscopy.impl.FileSystemCopyTaskImpl.perform(FileSystemCopyTaskImpl.java:316)
  at org.eclipse.oomph.setup.internal.core.SetupTaskPerformer.performNeededTask(SetupTaskPerformer.java:2869)
   ...
Caused by: java.nio.file.NoSuchFileException: /home/osboxes/oasp/software/java/man/ja
  at sun.nio.fs.UnixException.translateToIOException(UnixException.java:86)
  at sun.nio.fs.UnixException.rethrowAsIOException(UnixException.java:102)
  at sun.nio.fs.UnixException.rethrowAsIOException(UnixException.java:107)
  at sun.nio.fs.UnixCopyFile.copyLink(UnixCopyFile.java:326)
  at sun.nio.fs.UnixCopyFile.copy(UnixCopyFile.java:576)
  at sun.nio.fs.UnixFileSystemProvider.copy(UnixFileSystemProvider.java:253)
  at java.nio.file.Files.copy(Files.java:1274)
  at com.github.maybeec.oomph.task.fscopy.core.impl.FSCopyUtilImpl$1.visitFile(FSCopyUtilImpl.java:79)
  at com.github.maybeec.oomph.task.fscopy.core.impl.FSCopyUtilImpl$1.visitFile(FSCopyUtilImpl.java:1)
  at java.nio.file.Files.walkFileTree(Files.java:2670)
  at java.nio.file.Files.walkFileTree(Files.java:2742)
  at com.github.maybeec.oomph.task.fscopy.core.impl.FSCopyUtilImpl.fileWalkCopy(FSCopyUtilImpl.java:67)
  at com.github.maybeec.oomph.task.fscopy.core.impl.FSCopyUtilImpl.copy(FSCopyUtilImpl.java:47)
  at com.github.maybeec.oomph.task.fscopy.impl.FileSystemCopyTaskImpl.perform(FileSystemCopyTaskImpl.java:316)
   ...
```

The exception is thrown when trying to copy the manpage folder `man/ja`, which is a symbolic link to folder `ja_JP.UTF-8`:

```shell
osboxes@osboxes$ ls -lad /usr/lib/jvm/java-8-oracle/man/ja*
lrwxrwxrwx 1 root root   11 Feb 21 15:54 /usr/lib/jvm/java-8-oracle/man/ja -> ja_JP.UTF-8
drwxr-xr-x 3 root root 4096 Feb 21 15:54 /usr/lib/jvm/java-8-oracle/man/ja_JP.UTF-8
```
